apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    category: job
  name: test-job
  namespace: argocd
spec:
  destination:
    namespace: etc
    server: https://kubernetes.default.svc
  project: default
  source:
    path: batch
    repoURL: https://github.com/pjloveshiphop/k8s-practice.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  directory:
    recurse: true
