apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    name: kafka
spec:
  selector:
    app: kafka
    id: "0"
  ports:
  - port: 9092
    name: kafka-port
  type: LoadBalancer
