apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: monitoring
spec:
  project: default
  source:
    path: prometheus/
    repoURL: https://github.com/pjloveshiphop/k8s-practice.git
    targetRevision: HEAD
    directory:
      recurse: false # <--- Here
  destination:
    namespace: '*'
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true